apiVersion: v1
kind: ConfigMap
metadata:
  name: foodflow-config
  namespace: food-app
data:
  SPRING_PROFILES_ACTIVE: prod
  MYSQL_HOST: mysql-service
  MYSQL_PORT: "3306"
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
