apiVersion: v1
kind: Secret
metadata:
  name: foodflow-secrets
  namespace: food-app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: foodflow_db
  JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
