server:
  port: 8080

spring:
  application:
    name: foodflow-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/foodflow_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: dummy_user
    password: dummy_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Actuator configuration
management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Custom application properties
app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: 86400000 # 24 hours
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}



stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

