name: Deploy to Amazon EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: foodiefy-eks-cluster
  ECR_REPOSITORY_FRONTEND: foodiefy-frontend
  ECR_REPOSITORY_BACKEND: foodiefy-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Backend Image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd backend
          mvn clean package -DskipTests
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:${{ github.sha }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:${{ github.sha }}

      - name: Build, tag, and push Frontend Image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd frontend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:${{ github.sha }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:${{ github.sha }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Update Deployment File (Image Tags)
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          sed -i "s|image: foodflow-backend:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:${{ github.sha }}|" k8s/deployment.yaml
          sed -i "s|image: foodflow-frontend:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:${{ github.sha }}|" k8s/deployment.yaml

      - name: Deploy to Amazon EKS
        run: |
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/mysql-stateful.yaml
          kubectl apply -f k8s/config.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml

      - name: Verify Deployment
        run: kubectl rollout status deployment/backend -n food-app
